### ISSUE TITLE
Errors when attempting to add driver for Astromechanics focuser

### ISSUE THREAD

**Issue by mikez104** [indilib/indi#1104]
Trying to follow the instructions on ```https://indilib.org/devices/focusers/astromechanics-canon-lens-controller.html```
I followed the link to report issues which brought me here.
When I try and issue the command listed on this page which is 
`sudo add-apt-repository ppa:mutlaqja/ppa`
It results in this error.
```Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 95, in <module>
    sp = SoftwareProperties(options=options)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 109, in __init__
    self.reload_sourceslist()
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 599, in reload_sourceslist
    self.distro.get_sources(self.sourceslist)
  File "/usr/lib/python3/dist-packages/aptsources/distro.py", line 93, in get_sources
    (self.id, self.codename))
aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Raspbian/buster
```
I'd really love to get this working and if anyone could look into this that would be great.

**Comment by knro** [comment]
The PPA is for Ubuntu, not Debian. You can compile from source code or find a debian repo for the driver.
