### ISSUE TITLE
INDI indi_v4l2_ccd segfault when exposing a GRBG formated frame in Ekos

### ISSUE THREAD

**Issue by sk-astro-nut** [indilib/indi#1939]
**Describe the bug**
When capturing an image in GRBG format using NexImage 10 camera the indi_v4l2_ccd drivers crashes with a segment fault . 

**To Reproduce**
Open Kstars 
Connect to INDI and to camera 
In the capture Tab of the camera driver set the capture type to GRGB Full resolution ( happens with other 
resolutions as well but not as consistently with lower resolutions ) 
Capture an exposure
On capturing the exposure indi_v4l2_ccd crashes with a seg fault

Inspecting the core dump it appears that it is failing in bayer_grbg_to_rgb24
I took a look through the routine libs/indibase/stream/ccvt_misc.c and was able to follow some of what the code
is trying to do. It looks like there are some indexing issues with the edge cases ( top/bottom/left/right and corners ) 
For example when reading the top right corner it will be attempting to read src[-1] ( src[(row-1)*width+col] where  row = 0 and 
col = width -1 ) there are other spots where it will try to index past the end of the buffer ( bottom row src[(row+)*width+col] )
I believe there  is also a check for row==WIDTH that i think should be row==HIGHT

Camera works ok with most other modes ( has another issue with 16b gray scale at full res but is ok at lower res ) 

**Expected behavior**
Exposure returned to application

**Screenshots**

![capture page](https://github.com/indilib/indi/assets/145941988/930029fb-2b8f-447c-a44f-60ed0c980a12)

![capture settings](https://github.com/indilib/indi/assets/145941988/cc735ebf-4116-4cb2-947a-f3a89d6a8944)

**Desktop (please complete the following information):**
 - OS: Lubuntu 23.04
Linux host 6.2.0-33-generic #33-Ubuntu SMP PREEMPT_DYNAMIC Tue Sep  5 14:49:19 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

 - Version
     Kstars Build: 2023-08-18T09:00:48Z
     INDI Library 2.0.4

**Log Files**
Make sure to enable logging and include log files https://indilib.org/support/logs-submission.html

'''
backtrace
#0  0x00007fc0973b7292 in bayer_grbg_to_rgb24 ()
   from /lib/x86_64-linux-gnu/libindidriver.so.2
#1  0x00007fc0973c7311 in V4L2_Builtin_Decoder::decode(unsigned char*, v4l2_buffer*, bool) () from /lib/x86_64-linux-gnu/libindidriver.so.2
#2  0x00007fc0973ba899 in INDI::V4L2_Base::read_frame(char*) ()
   from /lib/x86_64-linux-gnu/libindidriver.so.2
#3  0x00007fc0973bac21 in INDI::V4L2_Base::newFrame(int, void*) ()
   from /lib/x86_64-linux-gnu/libindidriver.so.2
#4  0x00007fc09745834d in ?? () from /lib/x86_64-linux-gnu/libindidriver.so.2
#5  0x00007fc0974607a2 in eventLoop () from /lib/x86_64-linux-gnu/libindidriver.so.2
#6  0x00007fc0973cb122 in main () from /lib/x86_64-linux-gnu/libindidriver.so.2
#7  0x00007fc096c23a90 in __libc_start_call_main (main=main@entry=0x7fc0973cafd0 <main>, 
    argc=argc@entry=1, argv=argv@entry=0x7ffd55da5a18)
    at ../sysdeps/nptl/libc_start_call_main.h:58
#8  0x00007fc096c23b49 in __libc_start_main_impl (main=0x7fc0973cafd0 <main>, argc=1, 
    argv=0x7ffd55da5a18, init=<optimized out>, fini=<optimized out>, 
    rtld_fini=<optimized out>, stack_end=0x7ffd55da5a08) at ../csu/libc-start.c:360
#9  0x000055cf322754e5 in ?? ()
'''

[lsusb.log](https://github.com/indilib/indi/files/12710131/lsusb.log)
[v4l_info.log](https://github.com/indilib/indi/files/12710139/v4l_info.log)
[v4l2_list_format_ext.log](https://github.com/indilib/indi/files/12710140/v4l2_list_format_ext.log)

**Comment by sk-astro-nut** [comment]
ppa stable

**Comment by sk-astro-nut** [comment]
ppa stable
