### ISSUE TITLE
QHY9S indi_qhy_ccd driver not working

### ISSUE THREAD

**Issue by mp77** [indilib/indi#43]
I have an issue with the QHY driver. 
Connecting to the CCD works, except 

`2016-07-13T18:26:26: Driver indi_qhy_ccd: get info from camera failure QHY9S-0-M-
`
Starting exposure works.
At downloading driver restarts...

indiserver -vv: 
```
2016-07-13T18:16:42: Driver indi_qhy_ccd: read <setNumberVector device='QHY CCD QHY9S-0-M-' name='CCD_EXPOSURE'>
2016-07-13T18:16:42: Client 0: queuing <setNumberVector device='QHY CCD QHY9S-0-M-' name='CCD_EXPOSURE'>
2016-07-13T18:16:42: Client 0: sending <setNumberVector device="QHY CCD QHY9S-0-M-" name=
2016-07-13T18:16:42: Driver indi_qhy_ccd: read <message device='QHY CCD QHY9S-0-M-' name=''>
2016-07-13T18:16:42: Client 0: queuing <message device='QHY CCD QHY9S-0-M-' name=''>
2016-07-13T18:16:42: Client 0: sending <message device="QHY CCD QHY9S-0-M-" timestamp="20
2016-07-13T18:16:42: Driver indi_qhy_ccd: read <setNumberVector device='QHY CCD QHY9S-0-M-' name='CCD_TEMPERATURE'>
2016-07-13T18:16:42: Client 0: queuing <setNumberVector device='QHY CCD QHY9S-0-M-' name='CCD_TEMPERATURE'>
2016-07-13T18:16:42: Driver indi_qhy_ccd: read <setNumberVector device='QHY CCD QHY9S-0-M-' name='CCD_COOLER_POWER'>
2016-07-13T18:16:42: Client 0: queuing <setNumberVector device='QHY CCD QHY9S-0-M-' name='CCD_COOLER_POWER'>
2016-07-13T18:16:42: Client 0: sending <setNumberVector device="QHY CCD QHY9S-0-M-" name=
2016-07-13T18:16:42: Client 0: sending <setNumberVector device="QHY CCD QHY9S-0-M-" name=
2016-07-13T18:16:43: Driver indi_qhy_ccd: read <message device='QHY CCD QHY9S-0-M-' name=''>
2016-07-13T18:16:43: Client 0: queuing <message device='QHY CCD QHY9S-0-M-' name=''>
2016-07-13T18:16:43: Client 0: sending <message device="QHY CCD QHY9S-0-M-" timestamp="20
2016-07-13T18:16:43: Driver indi_qhy_ccd: read <setNumberVector device='QHY CCD QHY9S-0-M-' name='CCD_EXPOSURE'>
2016-07-13T18:16:43: Client 0: queuing <setNumberVector device='QHY CCD QHY9S-0-M-' name='CCD_EXPOSURE'>
2016-07-13T18:16:43: Client 0: sending <setNumberVector device="QHY CCD QHY9S-0-M-" name=
2016-07-13T18:16:43: Driver indi_qhy_ccd: read <message device='QHY CCD QHY9S-0-M-' name=''>
2016-07-13T18:16:43: Client 0: queuing <message device='QHY CCD QHY9S-0-M-' name=''>
2016-07-13T18:16:43: Client 0: sending <message device="QHY CCD QHY9S-0-M-" timestamp="20
2016-07-13T18:16:43: Driver indi_qhy_ccd: read <setNumberVector device='QHY CCD QHY9S-0-M-' name='CCD_TEMPERATURE'>
2016-07-13T18:16:43: Client 0: queuing <setNumberVector device='QHY CCD QHY9S-0-M-' name='CCD_TEMPERATURE'>
2016-07-13T18:16:43: Driver indi_qhy_ccd: read <setNumberVector device='QHY CCD QHY9S-0-M-' name='CCD_COOLER_POWER'>
2016-07-13T18:16:43: Client 0: queuing <setNumberVector device='QHY CCD QHY9S-0-M-' name='CCD_COOLER_POWER'>
2016-07-13T18:16:43: Client 0: sending <setNumberVector device="QHY CCD QHY9S-0-M-" name=
2016-07-13T18:16:43: Client 0: sending <setNumberVector device="QHY CCD QHY9S-0-M-" name=
2016-07-13T18:16:44: Driver indi_qhy_ccd: read <message device='QHY CCD QHY9S-0-M-' name=''>
2016-07-13T18:16:44: Client 0: queuing <message device='QHY CCD QHY9S-0-M-' name=''>
2016-07-13T18:16:44: Driver indi_qhy_ccd: read <setNumberVector device='QHY CCD QHY9S-0-M-' name='CCD_EXPOSURE'>
2016-07-13T18:16:44: Client 0: queuing <setNumberVector device='QHY CCD QHY9S-0-M-' name='CCD_EXPOSURE'>
2016-07-13T18:16:44: Client 0: sending <message device="QHY CCD QHY9S-0-M-" timestamp="20
2016-07-13T18:16:44: Client 0: sending <setNumberVector device="QHY CCD QHY9S-0-M-" name=
2016-07-13T18:16:44: Driver indi_qhy_ccd: read <message device='QHY CCD QHY9S-0-M-' name=''>
2016-07-13T18:16:44: Client 0: queuing <message device='QHY CCD QHY9S-0-M-' name=''>
2016-07-13T18:16:44: Driver indi_qhy_ccd: read <setNumberVector device='QHY CCD QHY9S-0-M-' name='CCD_TEMPERATURE'>
2016-07-13T18:16:44: Client 0: queuing <setNumberVector device='QHY CCD QHY9S-0-M-' name='CCD_TEMPERATURE'>
2016-07-13T18:16:44: Driver indi_qhy_ccd: read <setNumberVector device='QHY CCD QHY9S-0-M-' name='CCD_COOLER_POWER'>
2016-07-13T18:16:44: Client 0: queuing <setNumberVector device='QHY CCD QHY9S-0-M-' name='CCD_COOLER_POWER'>
2016-07-13T18:16:44: Client 0: sending <message device="QHY CCD QHY9S-0-M-" timestamp="20
2016-07-13T18:16:44: Client 0: sending <setNumberVector device="QHY CCD QHY9S-0-M-" name=
2016-07-13T18:16:44: Client 0: sending <setNumberVector device="QHY CCD QHY9S-0-M-" name=
2016-07-13T18:16:45: Driver indi_qhy_ccd: read <message device='QHY CCD QHY9S-0-M-' name=''>
2016-07-13T18:16:45: Client 0: queuing <message device='QHY CCD QHY9S-0-M-' name=''>
2016-07-13T18:16:45: Driver indi_qhy_ccd: read <setNumberVector device='QHY CCD QHY9S-0-M-' name='CCD_EXPOSURE'>
2016-07-13T18:16:45: Client 0: queuing <setNumberVector device='QHY CCD QHY9S-0-M-' name='CCD_EXPOSURE'>
2016-07-13T18:16:45: Client 0: sending <message device="QHY CCD QHY9S-0-M-" timestamp="20
2016-07-13T18:16:45: Client 0: sending <setNumberVector device="QHY CCD QHY9S-0-M-" name=
2016-07-13T18:16:45: Driver indi_qhy_ccd: read <message device='QHY CCD QHY9S-0-M-' name=''>
2016-07-13T18:16:45: Client 0: queuing <message device='QHY CCD QHY9S-0-M-' name=''>
2016-07-13T18:16:45: Driver indi_qhy_ccd: read <setNumberVector device='QHY CCD QHY9S-0-M-' name='CCD_TEMPERATURE'>
2016-07-13T18:16:45: Client 0: queuing <setNumberVector device='QHY CCD QHY9S-0-M-' name='CCD_TEMPERATURE'>
2016-07-13T18:16:45: Driver indi_qhy_ccd: read <setNumberVector device='QHY CCD QHY9S-0-M-' name='CCD_COOLER_POWER'>
2016-07-13T18:16:45: Client 0: queuing <setNumberVector device='QHY CCD QHY9S-0-M-' name='CCD_COOLER_POWER'>
2016-07-13T18:16:45: Client 0: sending <message device="QHY CCD QHY9S-0-M-" timestamp="20
2016-07-13T18:16:45: Client 0: sending <setNumberVector device="QHY CCD QHY9S-0-M-" name=
2016-07-13T18:16:45: Client 0: sending <setNumberVector device="QHY CCD QHY9S-0-M-" name=
2016-07-13T18:16:46: Driver indi_qhy_ccd: read <message device='QHY CCD QHY9S-0-M-' name=''>
2016-07-13T18:16:46: Client 0: queuing <message device='QHY CCD QHY9S-0-M-' name=''>
2016-07-13T18:16:46: Driver indi_qhy_ccd: read <setNumberVector device='QHY CCD QHY9S-0-M-' name='CCD_EXPOSURE'>
2016-07-13T18:16:46: Client 0: queuing <setNumberVector device='QHY CCD QHY9S-0-M-' name='CCD_EXPOSURE'>
2016-07-13T18:16:46: Client 0: sending <message device="QHY CCD QHY9S-0-M-" timestamp="20
2016-07-13T18:16:46: Client 0: sending <setNumberVector device="QHY CCD QHY9S-0-M-" name=
2016-07-13T18:16:46: Driver indi_qhy_ccd: read <message device='QHY CCD QHY9S-0-M-' name=''>
2016-07-13T18:16:46: Client 0: queuing <message device='QHY CCD QHY9S-0-M-' name=''>
2016-07-13T18:16:46: Driver indi_qhy_ccd: read <setNumberVector device='QHY CCD QHY9S-0-M-' name='CCD_TEMPERATURE'>
2016-07-13T18:16:46: Client 0: queuing <setNumberVector device='QHY CCD QHY9S-0-M-' name='CCD_TEMPERATURE'>
2016-07-13T18:16:46: Driver indi_qhy_ccd: read <setNumberVector device='QHY CCD QHY9S-0-M-' name='CCD_COOLER_POWER'>
2016-07-13T18:16:46: Client 0: queuing <setNumberVector device='QHY CCD QHY9S-0-M-' name='CCD_COOLER_POWER'>
2016-07-13T18:16:46: Client 0: sending <message device="QHY CCD QHY9S-0-M-" timestamp="20
2016-07-13T18:16:46: Client 0: sending <setNumberVector device="QHY CCD QHY9S-0-M-" name=
2016-07-13T18:16:46: Client 0: sending <setNumberVector device="QHY CCD QHY9S-0-M-" name=
2016-07-13T18:16:47: Driver indi_qhy_ccd: read <message device='QHY CCD QHY9S-0-M-' name=''>
2016-07-13T18:16:47: Client 0: queuing <message device='QHY CCD QHY9S-0-M-' name=''>
2016-07-13T18:16:47: Driver indi_qhy_ccd: read <setNumberVector device='QHY CCD QHY9S-0-M-' name='CCD_EXPOSURE'>
2016-07-13T18:16:47: Client 0: queuing <setNumberVector device='QHY CCD QHY9S-0-M-' name='CCD_EXPOSURE'>
2016-07-13T18:16:47: Client 0: sending <message device="QHY CCD QHY9S-0-M-" timestamp="20
2016-07-13T18:16:47: Client 0: sending <setNumberVector device="QHY CCD QHY9S-0-M-" name=
2016-07-13T18:16:47: Driver indi_qhy_ccd: read <message device='QHY CCD QHY9S-0-M-' name=''>
2016-07-13T18:16:47: Client 0: queuing <message device='QHY CCD QHY9S-0-M-' name=''>
2016-07-13T18:16:47: Driver indi_qhy_ccd: read <setNumberVector device='QHY CCD QHY9S-0-M-' name='CCD_TEMPERATURE'>
2016-07-13T18:16:47: Client 0: queuing <setNumberVector device='QHY CCD QHY9S-0-M-' name='CCD_TEMPERATURE'>
2016-07-13T18:16:47: Driver indi_qhy_ccd: read <setNumberVector device='QHY CCD QHY9S-0-M-' name='CCD_COOLER_POWER'>
2016-07-13T18:16:47: Client 0: queuing <setNumberVector device='QHY CCD QHY9S-0-M-' name='CCD_COOLER_POWER'>
2016-07-13T18:16:47: Client 0: sending <message device="QHY CCD QHY9S-0-M-" timestamp="20
2016-07-13T18:16:47: Client 0: sending <setNumberVector device="QHY CCD QHY9S-0-M-" name=
2016-07-13T18:16:47: Client 0: sending <setNumberVector device="QHY CCD QHY9S-0-M-" name=
2016-07-13T18:16:48: Driver indi_qhy_ccd: read <message device='QHY CCD QHY9S-0-M-' name=''>
2016-07-13T18:16:48: Client 0: queuing <message device='QHY CCD QHY9S-0-M-' name=''>
2016-07-13T18:16:48: Driver indi_qhy_ccd: read <setNumberVector device='QHY CCD QHY9S-0-M-' name='CCD_EXPOSURE'>
2016-07-13T18:16:48: Client 0: queuing <setNumberVector device='QHY CCD QHY9S-0-M-' name='CCD_EXPOSURE'>
2016-07-13T18:16:48: Client 0: sending <message device="QHY CCD QHY9S-0-M-" timestamp="20
2016-07-13T18:16:48: Client 0: sending <setNumberVector device="QHY CCD QHY9S-0-M-" name=
2016-07-13T18:16:48: Driver indi_qhy_ccd: read <message device='QHY CCD QHY9S-0-M-' name=''>
2016-07-13T18:16:48: Client 0: queuing <message device='QHY CCD QHY9S-0-M-' name=''>
2016-07-13T18:16:48: Driver indi_qhy_ccd: read <setNumberVector device='QHY CCD QHY9S-0-M-' name='CCD_TEMPERATURE'>
2016-07-13T18:16:48: Client 0: queuing <setNumberVector device='QHY CCD QHY9S-0-M-' name='CCD_TEMPERATURE'>
2016-07-13T18:16:48: Driver indi_qhy_ccd: read <setNumberVector device='QHY CCD QHY9S-0-M-' name='CCD_COOLER_POWER'>
2016-07-13T18:16:48: Client 0: queuing <setNumberVector device='QHY CCD QHY9S-0-M-' name='CCD_COOLER_POWER'>
2016-07-13T18:16:48: Client 0: sending <message device="QHY CCD QHY9S-0-M-" timestamp="20
2016-07-13T18:16:48: Client 0: sending <setNumberVector device="QHY CCD QHY9S-0-M-" name=
2016-07-13T18:16:48: Client 0: sending <setNumberVector device="QHY CCD QHY9S-0-M-" name=
2016-07-13T18:16:49: Driver indi_qhy_ccd: read <message device='QHY CCD QHY9S-0-M-' name=''>
2016-07-13T18:16:49: Client 0: queuing <message device='QHY CCD QHY9S-0-M-' name=''>
2016-07-13T18:16:49: Driver indi_qhy_ccd: read <setNumberVector device='QHY CCD QHY9S-0-M-' name='CCD_EXPOSURE'>
2016-07-13T18:16:49: Client 0: queuing <setNumberVector device='QHY CCD QHY9S-0-M-' name='CCD_EXPOSURE'>
2016-07-13T18:16:49: Client 0: sending <message device="QHY CCD QHY9S-0-M-" timestamp="20
2016-07-13T18:16:49: Client 0: sending <setNumberVector device="QHY CCD QHY9S-0-M-" name=
2016-07-13T18:17:00: Driver indi_qhy_ccd: stderr EOF
2016-07-13T18:17:00: Driver indi_qhy_ccd: restart #1
2016-07-13T18:17:00: Driver indi_qhy_ccd: pid=2029 rfd=3 wfd=7 efd=8
2016-07-13T18:17:00: Driver indi_qhy_ccd: sending <getProperties version='1.7'/>

2016-07-13T18:17:00: Driver indi_qhy_ccd: get info from camera failure QHY9S-0-M-
2016-07-13T18:17:00: Driver indi_qhy_ccd: read <getProperties device='Telescope Simulator' name='EQUATORIAL_EOD_COORD'>
2016-07-13T18:17:00: Driver indi_qhy_ccd: snooping on Telescope Simulator.EQUATORIAL_EOD_COORD
2016-07-13T18:17:00: Driver indi_qhy_ccd: read <getProperties device='Telescope Simulator' name='TELESCOPE_INFO'>
2016-07-13T18:17:00: Driver indi_qhy_ccd: snooping on Telescope Simulator.TELESCOPE_INFO
2016-07-13T18:17:00: Driver indi_qhy_ccd: read <getProperties device='CCD Simulator' name='FILTER_SLOT'>
2016-07-13T18:17:00: Driver indi_qhy_ccd: snooping on CCD Simulator.FILTER_SLOT
2016-07-13T18:17:00: Driver indi_qhy_ccd: read <getProperties device='CCD Simulator' name='FILTER_NAME'>
2016-07-13T18:17:00: Driver indi_qhy_ccd: snooping on CCD Simulator.FILTER_NAME
2016-07-13T18:17:00: Driver indi_qhy_ccd: read <defSwitchVector device='QHY CCD QHY9S-0-M-' name='CONNECTION'>
2016-07-13T18:17:00: Client 0: queuing <defSwitchVector device='QHY CCD QHY9S-0-M-' name='CONNECTION'>
2016-07-13T18:17:00: Driver indi_qhy_ccd: read <defTextVector device='QHY CCD QHY9S-0-M-' name='DRIVER_INFO'>
2016-07-13T18:17:00: Client 0: queuing <defTextVector device='QHY CCD QHY9S-0-M-' name='DRIVER_INFO'>
2016-07-13T18:17:00: Driver indi_qhy_ccd: read <defSwitchVector device='QHY CCD QHY9S-0-M-' name='DEBUG'>
2016-07-13T18:17:00: Client 0: queuing <defSwitchVector device='QHY CCD QHY9S-0-M-' name='DEBUG'>
2016-07-13T18:17:00: Driver indi_qhy_ccd: read <defSwitchVector device='QHY CCD QHY9S-0-M-' name='SIMULATION'>
2016-07-13T18:17:00: Client 0: queuing <defSwitchVector device='QHY CCD QHY9S-0-M-' name='SIMULATION'>
2016-07-13T18:17:00: Driver indi_qhy_ccd: read <defSwitchVector device='QHY CCD QHY9S-0-M-' name='CONFIG_PROCESS'>
2016-07-13T18:17:00: Client 0: queuing <defSwitchVector device='QHY CCD QHY9S-0-M-' name='CONFIG_PROCESS'>
2016-07-13T18:17:00: Client 0: sending <defSwitchVector device="QHY CCD QHY9S-0-M-" name=
2016-07-13T18:17:00: Driver indi_qhy_ccd: read <defTextVector device='QHY CCD QHY9S-0-M-' name='ACTIVE_DEVICES'>
2016-07-13T18:17:00: Client 0: queuing <defTextVector device='QHY CCD QHY9S-0-M-' name='ACTIVE_DEVICES'>
2016-07-13T18:17:00: Client 0: sending <defTextVector device="QHY CCD QHY9S-0-M-" name="D
2016-07-13T18:17:00: Client 0: sending <defSwitchVector device="QHY CCD QHY9S-0-M-" name=
2016-07-13T18:17:00: Client 0: sending <defSwitchVector device="QHY CCD QHY9S-0-M-" name=
2016-07-13T18:17:00: Driver indi_qhy_ccd: read <setTextVector device='QHY CCD QHY9S-0-M-' name='ACTIVE_DEVICES'>
2016-07-13T18:17:00: Client 0: queuing <setTextVector device='QHY CCD QHY9S-0-M-' name='ACTIVE_DEVICES'>
2016-07-13T18:17:00: Driver indi_qhy_ccd: read <getProperties device='Telescope Simulator' name='EQUATORIAL_EOD_COORD'>
2016-07-13T18:17:00: Driver indi_qhy_ccd: read <getProperties device='Telescope Simulator' name='TELESCOPE_INFO'>
2016-07-13T18:17:00: Driver indi_qhy_ccd: read <getProperties device='QHY CCD QHY9S-0-M-' name='FILTER_SLOT'>
2016-07-13T18:17:00: Driver indi_qhy_ccd: snooping on QHY CCD QHY9S-0-M-.FILTER_SLOT
2016-07-13T18:17:00: Driver indi_qhy_ccd: read <getProperties device='QHY CCD QHY9S-0-M-' name='FILTER_NAME'>
2016-07-13T18:17:00: Driver indi_qhy_ccd: snooping on QHY CCD QHY9S-0-M-.FILTER_NAME
2016-07-13T18:17:00: Client 0: sending <defSwitchVector device="QHY CCD QHY9S-0-M-" name=
2016-07-13T18:17:00: Client 0: sending <defTextVector device="QHY CCD QHY9S-0-M-" name="A
2016-07-13T18:17:00: Client 0: sending <setTextVector device="QHY CCD QHY9S-0-M-" name="A
2016-07-13T18:17:12: Client 0: read <newSwitchVector device='QHY CCD QHY9S-0-M-' name='CONNECTION'>
2016-07-13T18:17:12: Driver indi_qhy_ccd: queuing responsible for <newSwitchVector device='QHY CCD QHY9S-0-M-' name='CONNECTION'>
2016-07-13T18:17:12: Driver indi_qhy_ccd: sending <newSwitchVector device="QHY CCD QHY9S-0-M-" name=
2016-07-13T18:17:12: Driver indi_qhy_ccd: read <setSwitchVector device='QHY CCD QHY9S-0-M-' name='CONNECTION'>
2016-07-13T18:17:12: Client 0: queuing <setSwitchVector device='QHY CCD QHY9S-0-M-' name='CONNECTION'>
2016-07-13T18:17:12: Client 0: sending <setSwitchVector device="QHY CCD QHY9S-0-M-" name=
2016-07-13T18:17:16: Client 0: read EOF
2016-07-13T18:17:16: Client 0: shut down complete - bye!
```

EKOS:
```
2016-07-13T18:26:15: Exposure done, downloading image... 
2016-07-13T18:26:14: CCD Temp: 4.35227 CCD RAW Cooling Power: 44.2586, CCD Cooling percentage: 17.3563 
2016-07-13T18:26:14: Taking a 1 seconds frame... 
2016-07-13T18:26:14: SetQHYCCDResolution camroix 0 camroiy 0 camroiwidth 3584 camroiheight 2574 
2016-07-13T18:26:14: SetQHYCCDBinMode 1x1 
2016-07-13T18:26:14: Current exposure time is 1000000.000000 us 
2016-07-13T18:26:13: CCD Temp: 4.00861 CCD RAW Cooling Power: 44.2586, CCD Cooling percentage: 17.3563 
2016-07-13T18:26:12: CCD Temp: 4.00861 CCD RAW Cooling Power: 44.2586, CCD Cooling percentage: 17.3563 
2016-07-13T18:26:11: CCD Temp: 3.52528 CCD RAW Cooling Power: 44.2586, CCD Cooling percentage: 17.3563 
2016-07-13T18:26:10: CCD Temp: 3.52528 CCD RAW Cooling Power: 24.4225, CCD Cooling percentage: 9.57743 
2016-07-13T18:26:09: CCD Temp: 2.7952 CCD RAW Cooling Power: 24.4225, CCD Cooling percentage: 9.57743 
```

I hope this makes sense to someone.

Marco

**Comment by mp77** [comment]
gdb backtrace:
```
pi@raspberrypi:~/libindi_1.2.0_rpi $ gdb --eval-command="set follow-fork-mode child" --args indiserver -v indi_qhy_ccd
GNU gdb (Raspbian 7.7.1+dfsg-5) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "arm-linux-gnueabihf".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from indiserver...Reading symbols from /usr/lib/debug//usr/bin/indiserver...done.
done.
(gdb) run
Starting program: /usr/bin/indiserver -v indi_qhy_ccd
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
2016-07-13T18:45:00: startup: /usr/bin/indiserver -v indi_qhy_ccd 
[New process 3246]
2016-07-13T18:45:00: Driver indi_qhy_ccd: pid=3246 rfd=3 wfd=6 efd=7
2016-07-13T18:45:00: listening to port 7624 on fd 4
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
process 3246 is executing new program: /usr/bin/indi_qhy_ccd
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
[New Thread 0x6b4c6450 (LWP 3247)]
[New Thread 0x6aaff450 (LWP 3248)]
2016-07-13T18:45:01: Driver indi_qhy_ccd: get info from camera failure QHY9S-0-M-
2016-07-13T18:45:01: Driver indi_qhy_ccd: snooping on Telescope Simulator.EQUATORIAL_EOD_COORD
2016-07-13T18:45:01: Driver indi_qhy_ccd: snooping on Telescope Simulator.TELESCOPE_INFO
2016-07-13T18:45:01: Driver indi_qhy_ccd: snooping on CCD Simulator.FILTER_SLOT
2016-07-13T18:45:01: Driver indi_qhy_ccd: snooping on CCD Simulator.FILTER_NAME
2016-07-13T18:45:01: Driver indi_qhy_ccd: snooping on QHY CCD QHY9S-0-M-.FILTER_SLOT
2016-07-13T18:45:01: Driver indi_qhy_ccd: snooping on QHY CCD QHY9S-0-M-.FILTER_NAME
2016-07-13T18:45:03: Client 0: new arrival from 192.168.0.6:64088 - welcome!
[New Thread 0x64899450 (LWP 3252)]
2016-07-13T18:45:04: Driver indi_qhy_ccd: recorder: setpixelformat 1497715271
2016-07-13T18:45:04: Driver indi_qhy_ccd: recorder: setsize 3584x2574
2016-07-13T18:45:04: Driver indi_qhy_ccd: recorder: setsize 3584x2574
2016-07-13T18:45:04: Driver indi_qhy_ccd: recorder: setsize 3584x2574

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x76ff7000 (LWP 3246)]
0x76fbbb78 in memcmp () from /usr/lib/arm-linux-gnueabihf/libarmmem.so
(gdb) bt
#0  0x76fbbb78 in memcmp () from /usr/lib/arm-linux-gnueabihf/libarmmem.so
#1  0x00000000 in ?? ()
(gdb)
```

**Comment by mp77** [comment]
After compiling the Github QHYCCD_Linux source on the Pi, it is working. Don't know exactly why...
